services:
  fgg-server:
    container_name: fgg-server
    image: fgg-service
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./logs:/app/logs
    networks:
      - fgg-network

networks:
  fgg-network:
    name: fgg-network
    external: true
