openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.13.0
paths:
  /games/{login}/wishlist:
    post:
      operationId: addUserWishlistGame
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      requestBody:
        $ref: '#/components/requestBodies/WishlistGameRequest'
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getUserWishlistGames
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/WishlistGamesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/{login}/current:
    get:
      operationId: getUserCurrentGame
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/all/current:
    get:
      operationId: getAllCurrentGame
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current/roll:
    post:
      operationId: rollNewCurrentGame
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current/finish:
    post:
      operationId: finishCurrentGame
      tags:
        - Games
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current/cancel:
    post:
      operationId: cancelCurrentGame
      tags:
        - Games
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current/rate:
    post:
      operationId: rateCurrentGame
      tags:
        - Games
      requestBody:
        $ref: '#/components/requestBodies/GameRateRequest'
      responses:
        '204':
          description: Success.
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/{login}/history:
    get:
      operationId: getUserGameHistory
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/GameHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WishlistGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
      required:
        - name
    WishlistGames:
      type: array
      items:
        $ref: '#/components/schemas/WishlistGame'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Duration:
      type: string
      format: duration
      example: PT2h10m5s
      description: The duration notation as defined by ISO 8601
    CurrentGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        state:
          type: string
          enum:
            - started
            - finished
            - cancelled
        timeSpent:
          $ref: '#/components/schemas/Duration'
        startDate:
          type: string
          format: date-time
      required:
        - name
        - state
        - timeSpent
        - startDate
    CurrentGameByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          currentGame:
            $ref: '#/components/schemas/CurrentGame'
        required:
          - login
    GameRate:
      type: object
      properties:
        rating:
          type: integer
          format: int
        reviewComment:
          type: string
      required:
        - rating
    GameHistoryEntry:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        action:
          type: string
        endState:
          type: string
          enum:
            - started
            - finished
            - cancelled
        timeSpent:
          $ref: '#/components/schemas/Duration'
        rating:
          type: integer
          format: int
        reviewComment:
          type: string
        createdDate:
          type: string
          format: date-time
      required:
        - name
        - action
        - timeSpent
        - createdDate
    GameHistoryEntries:
      type: array
      items:
        $ref: '#/components/schemas/GameHistoryEntry'
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    WishlistGamesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGames'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    CurrentGameResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGame'
    CurrentGameByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGameByLogins'
    GameHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameHistoryEntries'
  requestBodies:
    WishlistGameRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGame'
    GameRateRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameRate'
