openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.15.0
paths:
  /games/users/{login}/wishlist:
    post:
      operationId: addUserWishlistGame
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      requestBody:
        $ref: '#/components/requestBodies/WishlistGameRequest'
      responses:
        '201':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '422':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getUserWishlistGames
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/WishlistGamesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/users/{login}/current:
    get:
      operationId: getUserCurrentGame
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/users/{login}/history:
    get:
      operationId: getUserGameHistory
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/GameHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current:
    get:
      operationId: getAllCurrentGame
      tags:
        - Games
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/current/actions:
    post:
      operationId: createCurrentGameAction
      tags:
        - Games
      requestBody:
        $ref: '#/components/requestBodies/CurrentGameActionRequest'
      responses:
        '200':
          $ref: '#/components/responses/CurrentGameResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '422':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /games/reviews/{name}:
    get:
      operationId: getGameReview
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Name'
      responses:
        '200':
          $ref: '#/components/responses/GameReviewResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '422':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    put:
      operationId: putGameReview
      tags:
        - Games
      parameters:
        - $ref: '#/components/parameters/Name'
      requestBody:
        $ref: '#/components/requestBodies/GameReviewRequest'
      responses:
        '201':
          description: The game was rated for the first time.
        '204':
          description: The existing rating was replaced.
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '422':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WishlistGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
      required:
        - name
    WishlistGames:
      type: array
      items:
        $ref: '#/components/schemas/WishlistGame'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Duration:
      type: string
      format: duration
      example: PT2h10m5s
      description: The duration notation as defined by ISO 8601
    CurrentGame:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        timeSpent:
          $ref: '#/components/schemas/Duration'
        startDate:
          type: string
          format: date-time
      required:
        - name
        - timeSpent
        - startDate
    GameHistoryEntry:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        action:
          type: string
        endState:
          type: string
          enum:
            - started
            - finished
            - cancelled
        timeSpent:
          $ref: '#/components/schemas/Duration'
        createdDate:
          type: string
          format: date-time
      required:
        - name
        - action
        - timeSpent
        - createdDate
    GameHistoryEntries:
      type: array
      items:
        $ref: '#/components/schemas/GameHistoryEntry'
    CurrentGameByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          currentGame:
            $ref: '#/components/schemas/CurrentGame'
        required:
          - login
    CurrentGameAction:
      type: object
      properties:
        action:
          type: string
          enum:
            - start
            - finish
            - cancel
      required:
        - action
    GameReview:
      type: object
      properties:
        rating:
          type: integer
          format: int
          minimum: 1
          maximum: 10
        reviewComment:
          type: string
      required:
        - rating
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
    Name:
      name: name
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Name'
  responses:
    WishlistGamesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGames'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    CurrentGameResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGame'
    GameHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameHistoryEntries'
    CurrentGameByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGameByLogins'
    GameReviewResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameReview'
  requestBodies:
    WishlistGameRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WishlistGame'
    CurrentGameActionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CurrentGameAction'
    GameReviewRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GameReview'
