openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.13.0
paths:
  /wheel-effects/{login}/history:
    get:
      operationId: getUserWheelEffectHistory
      tags:
        - WheelEffects
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/WheelRowHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available:
    get:
      operationId: getAvailableWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/WheelRowsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll:
    post:
      operationId: rollAvailableWheelEffects
      tags:
        - WheelEffects
      requestBody:
        $ref: '#/components/requestBodies/WheelEffectRollRequest'
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelRowsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/count:
    get:
      operationId: getAvailableWheelEffectRollsCount
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/last:
    get:
      operationId: getLastRolledWheelEffects
      tags:
        - WheelEffects
      responses:
        '200':
          $ref: '#/components/responses/RolledWheelRowsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/last/clear:
    post:
      operationId: clearLastRolledWheelEffects
      tags:
        - WheelEffects
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /wheel-effects/available/roll/apply:
    post:
      operationId: applyAvailableWheelEffectRoll
      tags:
        - WheelEffects
      requestBody:
        $ref: '#/components/requestBodies/WheelRowApplyRequest'
      responses:
        '204':
          description: Success.
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    WheelRow:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        description:
          type: string
      required:
        - name
    WheelRowHistory:
      allOf:
        - $ref: '#/components/schemas/WheelRow'
        - type: object
          properties:
            appliedDate:
              type: string
              format: date-time
          required:
            - appliedDate
    WheelRowHistories:
      type: array
      items:
        $ref: '#/components/schemas/WheelRowHistory'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    WheelRows:
      type: array
      items:
        $ref: '#/components/schemas/WheelRow'
    WheelEffectRoll:
      type: object
      properties:
        isReroll:
          type: boolean
          default: false
    RolledWheelRow:
      allOf:
        - $ref: '#/components/schemas/WheelRow'
        - type: object
          properties:
            position:
              type: integer
              format: int
            rolledDate:
              type: string
              format: date-time
          required:
            - position
            - rolledDate
    RolledWheelRows:
      type: array
      items:
        $ref: '#/components/schemas/RolledWheelRow'
    Points:
      type: integer
      format: int
    WheelRowApply:
      type: object
      properties:
        wheelRowName:
          $ref: '#/components/schemas/Name'
        targetLogins:
          type: array
          items:
            $ref: '#/components/schemas/Login'
          minItems: 1
      required:
        - wheelRowName
        - targetLogins
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    WheelRowHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelRowHistories'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    WheelRowsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelRows'
    RolledWheelRowsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolledWheelRows'
    PointsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Points'
  requestBodies:
    WheelEffectRollRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelEffectRoll'
    WheelRowApplyRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WheelRowApply'
