openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.1.0
paths:
  /parties/{partyId}/effects/catalog:
    $ref: "../paths/effects/catalog.yaml"

  /parties/{partyId}/effects/catalog/removed:
    $ref: "../paths/effects/catalog/removed.yaml"

  /parties/{partyId}/effects/catalog/{id}:
    $ref: "../paths/effects/catalog/id.yaml"

  /parties/{partyId}/effects/{login}:
    $ref: "../paths/effects/login.yaml"

  /parties/{partyId}/effects/{login}/history:
    $ref: "../paths/effects/login/history.yaml"

  /parties/{partyId}/effects/{login}/{id}:
    $ref: "../paths/effects/login/id.yaml"

  /parties/{partyId}/effects/{login}/{id}/use:
    $ref: "../paths/effects/login/id/use.yaml"