openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.15.0
paths:
  /parties/{partyId}/games/users/{login}/wishlist:
    $ref: "../paths/games/users/login/wishlist.yaml"

  /parties/{partyId}/games/users/{login}/current:
    $ref: "../paths/games/users/login/current.yaml"

  /parties/{partyId}/games/users/{login}/history:
    $ref: "../paths/games/users/login/history.yaml"

  /parties/{partyId}/games/current:
    $ref: "../paths/games/current.yaml"

  /parties/{partyId}/games/current/actions:
    $ref: "../paths/games/current/actions.yaml"

  /parties/{partyId}/games/reviews/{name}:
    $ref: "../paths/games/reviews/name.yaml"
