openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.15.0
paths:
  /points/types:
    $ref: "../paths/points/types.yaml"

  /points/types/{name}:
    $ref: "../paths/points/types/name.yaml"

  /points/users/all:
    $ref: "../paths/points/users/all.yaml"

  /points/party/all:
    $ref: "../paths/points/party/all.yaml"

  /points/party/{name}:
    $ref: "../paths/points/party/name.yaml"

  /points/party/{name}/history:
    $ref: "../paths/points/party/name/history.yaml"

  /points/{login}:
    $ref: "../paths/points/login.yaml"

  /points/{login}/{name}:
    $ref: "../paths/points/login/name.yaml"

  /points/{login}/{name}/history:
    $ref: "../paths/points/login/name/history.yaml"