openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.15.0
paths:
  /points/types:
    $ref: "../paths/points/types.yaml"

  /points/types/{name}:
    $ref: "../paths/points/types/name.yaml"

  /points/users:
    $ref: "../paths/points/users.yaml"

  /points/users/{login}:
    $ref: "../paths/points/users/login.yaml"

  /points/users/{login}/types/{name}:
    $ref: "../paths/points/users/login/types/name.yaml"

  /points/users/{login}/types/{name}/history:
    $ref: "../paths/points/users/login/types/name/history.yaml"

  /points/party:
    $ref: "../paths/points/party.yaml"

  /points/party/types/{name}:
    $ref: "../paths/points/party/types/name.yaml"

  /points/party/types/{name}/history:
    $ref: "../paths/points/party/types/name/history.yaml"