openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.3.0
paths:
  /system-parameters:
    $ref: "../paths/system-parameters.yaml"

  /system-parameters/{name}:
    $ref: "../paths/system-parameters/name.yaml"