openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.12.5
paths:
  /parties/{partyId}/timers/current:
    $ref: "../paths/timers/current.yaml"

  /parties/{partyId}/timers/current/start:
    $ref: "../paths/timers/current/start.yaml"

  /parties/{partyId}/timers/current/pause:
    $ref: "../paths/timers/current/pause.yaml"

  /parties/{partyId}/timers/reward:
    $ref: "../paths/timers/reward.yaml"
