openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.14.0
paths:
  /parties/{partyId}/wheel-effects/{login}/history:
    $ref: "../paths/wheel-effects/login/history.yaml"

  /parties/{partyId}/wheel-effects/available:
    $ref: "../paths/wheel-effects/available.yaml"

  /parties/{partyId}/wheel-effects/available/roll:
    $ref: "../paths/wheel-effects/available/roll.yaml"

  /parties/{partyId}/wheel-effects/available/roll/count:
    $ref: "../paths/wheel-effects/available/roll/count.yaml"

  /parties/{partyId}/wheel-effects/available/roll/last:
    $ref: "../paths/wheel-effects/available/roll/last.yaml"

  /parties/{partyId}/wheel-effects/available/roll/last/clear:
    $ref: "../paths/wheel-effects/available/roll/last/clear.yaml"

  /parties/{partyId}/wheel-effects/available/roll/apply:
    $ref: "../paths/wheel-effects/available/roll/apply.yaml"